spring:
  application:
    name: companies-crud
    profiles:
      default: default
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    hikari:
      connection-timeout: ${db.connection-timeout}
      maximum-pool-size: ${db.maximum-pool-size}
  config:
    import: "optional:configserver:http://localhost:7777"

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  servlet:
    context-path: /companies-crud
  port: 8081

eureka:
  instance:
    instance-id: "${spring.application.name}:${spring.application.instance_id:${random.value}}"
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
